@php
    /** $kind = 'recommendation' (regression) | 'scheduling' (decision tree) */
    $kind = $kind ?? 'recommendation';
    $technique = $kind === 'scheduling' ? 'Decision-Tree' : 'Regression';
    $groups = $kind === 'scheduling'
        ? [
            'Appointment' => ['Day of week', 'Time of day', 'Days booked in advance', 'Duration', 'Walk-in vs booked', 'Bill amount'],
            'Patient history' => ['Age', 'Number of prior visits', 'Number of prior no-shows'],
        ]
        : [
            'Symptoms' => ['Toothache', 'Sensitivity', 'Bleeding gums', 'Bad breath', 'Swelling'],
            'Oral-health habits' => ['Brushing per day', 'Flossing', 'Smoking', 'Sugar intake', 'Months since last cleaning'],
            'Clinical findings' => ['Visible plaque', 'Cavity / decay', 'Gum condition', 'Missing teeth', 'Existing fillings'],
            'Patient' => ['Age'],
        ];
@endphp
<details class="mt-2 text-[11px]">
    <summary class="cursor-pointer text-slate-400 hover:text-slate-600 list-none inline-flex items-center gap-1">
        <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path stroke-linecap="round" d="M12 11v5m0-8h.01"/></svg>
        Which data was used to compute this?
    </summary>
    <div class="mt-1.5 rounded-lg bg-slate-50 border border-slate-100 p-3 text-slate-500">
        <p>Decision-support only — generated by a <strong>{{ $technique }}</strong> model. The final decision is made by the dentist / staff. Inputs used:</p>
        <div class="mt-1.5 grid sm:grid-cols-2 gap-x-4 gap-y-1.5">
            @foreach ($groups as $title => $items)
                <div>
                    <div class="font-medium text-slate-600">{{ $title }}</div>
                    <div>{{ implode(', ', $items) }}</div>
                </div>
            @endforeach
        </div>
    </div>
</details>
