<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #0f172a; font-size: 13px; }
        .head { border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 18px; }
        .clinic { color: #2563eb; font-size: 20px; font-weight: bold; }
        .muted { color: #64748b; }
        .box { border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; margin-top: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 6px; }
        td { padding: 4px 0; vertical-align: top; }
        .label { color: #64748b; width: 170px; }
        .rec { font-size: 16px; font-weight: bold; }
        .foot { margin-top: 28px; font-size: 11px; color: #94a3b8; }
    </style>
</head>
<body>
    <div class="head">
        <div class="clinic">Bonoan&rsquo;s Dental Clinic</div>
        <div class="muted">Treatment Recommendation</div>
    </div>

    <table>
        <tr><td class="label">Patient</td><td>{{ $appointment->patient?->fullName() }}</td></tr>
        <tr><td class="label">Attending dentist</td><td>{{ $appointment->dentist?->name ?? '—' }}</td></tr>
        <tr><td class="label">Visit date</td><td>{{ $appointment->scheduled_at?->format('M j, Y g:i A') }}</td></tr>
        <tr><td class="label">Recommendation type</td><td>{{ $rec->source->label() }}</td></tr>
        <tr><td class="label">Issued</td><td>{{ $issuedAt->format('M j, Y g:i A') }}</td></tr>
    </table>

    <div class="box">
        <div class="rec">{{ $rec->recommendation }}</div>
        <table>
            @if ($rec->service)
                <tr><td class="label">Linked service</td><td>{{ $rec->service->name }} (₱{{ number_format((float) $rec->service->price, 2) }})</td></tr>
            @endif
            @if ($rec->priority)
                <tr><td class="label">Priority</td><td>{{ $rec->priority->label() }}</td></tr>
            @endif
            @if ($rec->follow_up_weeks)
                <tr><td class="label">Suggested follow-up</td><td>in about {{ $rec->follow_up_weeks }} week(s)</td></tr>
            @endif
            @if ($rec->suggested_at)
                <tr><td class="label">Proposed schedule</td><td>{{ $rec->suggested_at->format('l, M j, Y · g:i A') }}</td></tr>
            @endif
            @if ($rec->notes)
                <tr><td class="label">Notes</td><td>{{ $rec->notes }}</td></tr>
            @endif
        </table>
    </div>

    <div class="foot">
        This recommendation is a decision-support suggestion from the patient&rsquo;s dental care team and does not
        replace the final clinical judgment of the dentist. Generated by the Bonoan&rsquo;s Dental Clinic system.
    </div>
</body>
</html>
