<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    @php $isInvoice = $type === 'invoice'; @endphp
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #0f172a; font-size: 13px; }
        .head { display: flex; justify-content: space-between; border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 16px; }
        .clinic { color: #2563eb; font-size: 20px; font-weight: bold; }
        .muted { color: #64748b; }
        .doc-title { text-align: right; }
        .doc-title h1 { margin: 0; font-size: 18px; }
        table.meta td { padding: 2px 0; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 14px; }
        table.items th { text-align: left; background: #f1f5f9; padding: 8px; font-size: 12px; }
        table.items td { padding: 8px; border-bottom: 1px solid #e2e8f0; }
        .right { text-align: right; }
        .totals { width: 45%; margin-left: 55%; margin-top: 12px; }
        .totals td { padding: 4px 0; }
        .totals .grand { border-top: 2px solid #0f172a; font-size: 15px; font-weight: bold; }
        .paid-stamp { margin-top: 16px; color: #059669; font-weight: bold; font-size: 15px; }
        .foot { margin-top: 30px; font-size: 11px; color: #94a3b8; }
    </style>
</head>
<body>
    <div class="head">
        <div>
            <div class="clinic">Bonoan&rsquo;s Dental Clinic</div>
            <div class="muted">Pangasinan, Philippines</div>
        </div>
        <div class="doc-title">
            <h1>{{ $isInvoice ? 'Official Invoice' : 'Billing Statement' }}</h1>
            <div class="muted">{{ $isInvoice ? $statement->invoice_no : $statement->statement_no }}</div>
            <div class="muted">{{ ($isInvoice ? $statement->paid_at : $statement->issued_at)?->format('M j, Y') }}</div>
        </div>
    </div>

    <table class="meta">
        <tr><td class="muted" style="width:120px;">Patient</td><td>{{ $appointment->patient?->fullName() }}</td></tr>
        <tr><td class="muted">Visit date</td><td>{{ $appointment->scheduled_at?->format('M j, Y g:i A') }}</td></tr>
        <tr><td class="muted">Attending dentist</td><td>{{ $appointment->dentist?->name ?? '—' }}</td></tr>
        @unless ($isInvoice)
            <tr><td class="muted">Statement</td><td>{{ $statement->statement_no }}</td></tr>
        @endunless
    </table>

    <table class="items">
        <thead>
            <tr>
                <th>Description</th>
                <th class="right" style="width:60px;">Qty</th>
                <th class="right" style="width:110px;">Unit price</th>
                <th class="right" style="width:110px;">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($statement->items as $item)
                <tr>
                    <td>{{ $item->description }}</td>
                    <td class="right">{{ $item->quantity }}</td>
                    <td class="right">₱{{ number_format((float) $item->unit_price, 2) }}</td>
                    <td class="right">₱{{ number_format((float) $item->line_total, 2) }}</td>
                </tr>
            @empty
                <tr><td colspan="4" class="muted">No line items recorded.</td></tr>
            @endforelse
        </tbody>
    </table>

    <table class="totals">
        <tr><td class="muted">Subtotal</td><td class="right">₱{{ number_format((float) $statement->subtotal, 2) }}</td></tr>
        @if ((float) $statement->discount > 0)
            <tr><td class="muted">Discount</td><td class="right">− ₱{{ number_format((float) $statement->discount, 2) }}</td></tr>
        @endif
        <tr class="grand"><td>Total</td><td class="right">₱{{ number_format((float) $statement->total, 2) }}</td></tr>
        @if ($isInvoice)
            <tr><td class="muted">Amount paid</td><td class="right">₱{{ number_format($appointment->amountPaid(), 2) }}</td></tr>
        @endif
    </table>

    @if ($isInvoice)
        <div class="paid-stamp">✓ PAID IN FULL</div>
    @endif

    <div class="foot">
        @if ($statement->notes)<div>Notes: {{ $statement->notes }}</div>@endif
        Thank you for choosing Bonoan&rsquo;s Dental Clinic. This document was generated by the clinic system.
    </div>
</body>
</html>
