<?php

namespace App\Models;

use App\Enums\UserRole;
use Database\Factories\UserFactory;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

#[Fillable(['name', 'username', 'email', 'role', 'is_active', 'avatar_path', 'referral_code', 'referred_by_id', 'data_privacy_consent_at', 'password'])]
#[Hidden(['password', 'remember_token'])]
class User extends Authenticatable implements MustVerifyEmail
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'data_privacy_consent_at' => 'datetime',
            'password' => 'hashed',
            'role' => UserRole::class,
            'is_active' => 'boolean',
        ];
    }

    /**
     * Public URL of the uploaded avatar, or null if none.
     */
    public function avatarUrl(): ?string
    {
        return $this->avatar_path ? asset('storage/'.$this->avatar_path) : null;
    }

    /**
     * Up-to-two-letter initials, used for the fallback avatar.
     */
    public function initials(): string
    {
        $parts = preg_split('/\s+/', trim($this->name)) ?: [];
        $letters = array_map(fn ($p) => mb_substr($p, 0, 1), array_slice($parts, 0, 2));

        return strtoupper(implode('', $letters)) ?: 'U';
    }

    /**
     * Send the clinic-branded email verification notification.
     */
    public function sendEmailVerificationNotification(): void
    {
        $this->notify(new \App\Notifications\VerifyEmailNotification);
    }

    /**
     * Send the clinic-branded password-reset notification.
     */
    public function sendPasswordResetNotification($token): void
    {
        $this->notify(new \App\Notifications\ResetPasswordNotification($token));
    }

    /**
     * The patient record linked to this account (only for patient users).
     */
    public function patient(): HasOne
    {
        return $this->hasOne(Patient::class);
    }

    /**
     * The user (if any) whose referral code this account signed up with.
     */
    public function referredBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'referred_by_id');
    }

    /**
     * Sign-ups this user has generated by sharing their code (as the referrer).
     */
    public function referralsMade(): HasMany
    {
        return $this->hasMany(ReferralSignup::class, 'referrer_id')->latest();
    }

    /**
     * This user's own "I was referred" record (as the referred patient).
     */
    public function referralSignup(): HasOne
    {
        return $this->hasOne(ReferralSignup::class, 'referred_id');
    }

    /**
     * Every entry in this user's rewards-points ledger.
     */
    public function rewardTransactions(): HasMany
    {
        return $this->hasMany(RewardTransaction::class)->latest();
    }

    /**
     * Whether the user holds the given role.
     */
    public function hasRole(UserRole $role): bool
    {
        return $this->role === $role;
    }

    /**
     * Whether the user is part of clinic staff (anyone but a patient).
     */
    public function isStaff(): bool
    {
        return $this->role->isStaff();
    }

    /**
     * Whether the user may manage other users.
     */
    public function canManageUsers(): bool
    {
        return $this->role->canManageUsers();
    }

    /**
     * A simple status label combining verification and the active flag.
     */
    public function status(): string
    {
        return match (true) {
            ! $this->is_active => 'suspended',
            $this->email_verified_at === null => 'unverified',
            default => 'active',
        };
    }
}
